name: Android App Automation CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        api-level: [35]
        target: [default]

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 1.8
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 1.8

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '12'

      - name: Install Appium
        run: |
          npm install -g appium@1.28.2
          appium -v
          appium &>/dev/null &

      - name: Run Android Emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          target: ${{ matrix.target }}
          arch: x86_64
          profile: Nexus 6
          script: npx wdio run wdio.conf.js

