name: Android Emulator Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  android-tests:
    runs-on: macos-latest
    timeout-minutes: 35

    steps:
      # Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Install Java (needed for Android SDK + Appium)
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # Install Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Install Android SDK tools via Homebrew
      - name: Install Android SDK
        run: |
          brew install --cask android-sdk
          echo "ANDROID_HOME=/usr/local/share/android-sdk" >> $GITHUB_ENV
          echo "PATH=$ANDROID_HOME/platform-tools:$ANDROID_HOME/emulator:$PATH" >> $GITHUB_ENV

      # Install Android 15 emulator + system image
      - name: Install Android Emulator & System Image
        run: |
          yes | sdkmanager --licenses
          yes | sdkmanager "platform-tools" "platforms;android-35" "system-images;android-35;google_apis;x86_64" "emulator"
          echo "no" | avdmanager create avd -n emulator-5554 -k "system-images;android-35;google_apis;x86_64" --device "pixel"

      # Start emulator
      - name: Start Emulator
        run: |
          $ANDROID_HOME/emulator/emulator -avd emulator-5554 -no-audio -no-window -gpu swiftshader_indirect &
          adb wait-for-device
          adb shell input keyevent 82

      # Install Node dependencies
      - name: Install dependencies
        run: npm ci

      # Install Appium server & UiAutomator2 driver
      - name: Install Appium
        run: |
          npm install -g appium
          appium driver install uiautomator2

      # Run WDIO tests
      - name: Run WebDriverIO tests
        run: npx wdio run ./wdio.conf.js
