name: Android Emulator Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  android-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      # Checkout your repo
      - name: Checkout
        uses: actions/checkout@v4

      # Install Java (required for Android SDK & Appium)
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # Install Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Install Android SDK & platform tools
      - name: Install Android SDK
        run: |
          sudo apt-get update
          sudo apt-get install -yq wget tar unzip
          wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmdline-tools.zip
          mkdir -p $HOME/android-sdk/cmdline-tools
          unzip cmdline-tools.zip -d $HOME/android-sdk/cmdline-tools
          mv $HOME/android-sdk/cmdline-tools/cmdline-tools $HOME/android-sdk/cmdline-tools/latest

          echo "ANDROID_HOME=$HOME/android-sdk" >> $GITHUB_ENV
          echo "PATH=$HOME/android-sdk/cmdline-tools/latest/bin:$HOME/android-sdk/platform-tools:$HOME/android-sdk/emulator:$PATH" >> $GITHUB_ENV

      # Install Android 15 system image & create emulator
      - name: Install Android Emulator
        run: |
          sdkmanager --sdk_root=$HOME/android-sdk --licenses <<< "y"
          sdkmanager --sdk_root=$HOME/android-sdk "platform-tools" "platforms;android-35" "system-images;android-35;google_apis;x86_64" "emulator"

          echo "no" | avdmanager create avd -n emulator-5554 -k "system-images;android-35;google_apis;x86_64" --device "pixel"
      
      # Start emulator in background
      - name: Start Emulator
        run: |
          $HOME/android-sdk/emulator/emulator -avd emulator-5554 -no-audio -no-window -gpu swiftshader_indirect &
          adb wait-for-device
          adb shell input keyevent 82

      # Install dependencies
      - name: Install Node dependencies
        run: npm ci

      # Install Appium server + drivers
      - name: Install Appium
        run: |
          npm install -g appium
          appium driver install uiautomator2

      # Run WebDriverIO tests
      - name: Run WDIO tests
        run: npx wdio run ./wdio.conf.js
