name: Android WDIO Tests

on: push

jobs:
    run-mobile-tests:
        runs-on: macos-latest

        steps:
            - name: setup java
              uses: actions/setup-java@v3
              with:
                distribution: 'temurin'
                java-version: '17'

            - name: pull the project in to the runner
              uses: actions/checkout@v3

            - name: setup appium
              run: |
                npm install -g appium@2.19.0
                appium -v
                appium &>/dev/null &

            - name: run tests
              uses: reactivecircus/android-emulator-runner@v2
              with:
                api-level: 30  # Most stable API level
                target: google_apis  # Use Google APIs image
                arch: x86_64  # Required for newer API levels
                script: npx wdio run wdio.conf.js
                emulator-options: -no-window -gpu swiftshader_indirect -no-snapshot -noaudio -no-boot-anim
                disable-animations: true