name: Android Emulator Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  android-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'adoptopenjdk'

      - name: Cache Android SDK
        uses: actions/cache@v3
        with:
          path: |
            ~/.android
            ~/.gradle
            ~/.m2
          key: ${{ runner.os }}-android-sdk-${{ hashFiles('**/*.gradle*') }}

      - name: Install dependencies
        run: npm ci

      - name: Set up Android Emulator
        uses: ReactiveCircus/android-emulator-runner@v2
        with:
          api-level: 30
          target: google_apis
          arch: x86_64
          force-avd-creation: true
          emulator-options: -no-window -gpu off
          script: echo "Emulator started"

      - name: Start Appium Server
        run: |
          npx appium --session-override &
          sleep 10

      - name: Run WebDriverIO Tests
        run: npx wdio run wdio.conf.js
