name: Android Emulator CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  android-emulator:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up JDK
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # Set up Android SDK
      - name: Set up Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 33
          target: default
          arch: x86_64
          emulator-options: -no-window -gpu swiftshader_indirect

      # Kill any existing adb server
      - name: Restart ADB server
        run: |
          adb kill-server || true
          adb start-server

      # Start emulator
      - name: Start emulator
        run: |
          echo "Starting emulator..."
          $ANDROID_HOME/emulator/emulator -avd test -no-snapshot-load -no-window -gpu swiftshader_indirect &
          adb wait-for-device

          # Wait until boot completed
          boot_completed=""
          until [[ "$boot_completed" == "1" ]]; do
            boot_completed=$(adb shell getprop sys.boot_completed 2>/dev/null | tr -d '\r')
            echo "Waiting for emulator to boot..."
            sleep 5
          done
          echo "Emulator is ready!"

      # Run your tests
      - name: Run tests
        run: |
          echo "Run your Appium/WebDriverIO tests here"
