name: Android WDIO Tests

on: push

jobs:
    run-mobile-tests:
        runs-on: macos-latest

        steps:
            - name: pull the project in to the runner
              uses: actions/checkout@v3

            - name: setup appium
              run: |
                npm install -g appium@2.19.0
                appium -v
                appium &>/dev/null &
            
            - name: run tests
              uses: reactivecircus/android-emulator-runner@v2
              with:
                api-level: 35
                script: npx wdio run wdio.conf.js
