name: Android Automation Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  android-tests:
    runs-on: macos-latest   # ✅ macOS runner for hardware-accelerated emulator
    timeout-minutes: 60

    steps:
      # Step 1: Checkout code
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # Step 3: Install dependencies
      - name: Install Node.js dependencies
        run: npm ci

      # Step 4: Download Android SDK & start emulator
      - name: Launch Android Emulator
        uses: ReactiveCircus/android-emulator-runner@v2
        with:
          api-level: 30                     # ✅ Faster boot time than 33
          target: google_apis               # Can use 'default' for even faster boots
          arch: arm64-v8a
          profile: pixel_4
          script: |
            adb devices
            adb install ./app-debug.apk      # ✅ Replace with path to your APK
            npx appium --log-level info &    # ✅ Start Appium in background
            sleep 10                         # Give Appium time to start
            npx wdio run wdio.conf.js        # ✅ Run WDIO + Cucumber tests
