name: Android App Automation CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Appium
        run: |
          npm install -g appium@2.19.0
          appium -v
          appium &>/dev/null &

      - name: Run Android Emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 33
          target: google_apis  # Use Google APIs instead of default
          arch: arm64-v8a
          profile: Nexus 6
          script: |
            echo "Waiting for emulator..."
            $ANDROID_HOME/platform-tools/adb wait-for-device
            echo "Emulator devices:"
            $ANDROID_HOME/platform-tools/adb devices -l
            echo "Starting tests..."
            npx wdio run wdio.conf.js
          emulator-options: -no-window -gpu off -no-snapshot -noaudio -no-boot-anim
          disable-animations: true