name: Android Appium WDIO Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  android-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 45

    env:
      ANDROID_SDK_ROOT: /usr/local/lib/android/sdk

    steps:
      # 1️⃣ Checkout your repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # 3️⃣ Install dependencies
      - name: Install dependencies
        run: npm ci

      # 4️⃣ Setup Java 17 (required for Android SDK tools)
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # 5️⃣ Start Android emulator
      - name: Run Android Emulator
        uses: ReactiveCircus/android-emulator-runner@v2
        with:
          api-level: 30
          target: google_apis
          arch: x86_64
          force-avd-creation: true
          emulator-options: -no-window -gpu off
          disable-animations: true
          script: echo "Emulator started"

      # 6️⃣ Wait for emulator to fully boot
      - name: Wait for Emulator
        run: adb wait-for-device

      # 7️⃣ Install your app on emulator
      - name: Install APK
        run: adb install -r app/Demo\ app.apk

      # 8️⃣ Run WDIO tests
      - name: Run WDIO Tests
        run: npx wdio run wdio.conf.js
