name: CI/CD

on:
  workflow_dispatch:
    inputs:
      node-version:
        description: "Choose the Node.js version for the workflow"
        required: false
        default: "20"
        type: choice
        options:
          - "16"
          - "18"
          - "20"
          - "21"
      generate-report:
        description: "Choose whether to create and upload the test report"
        required: false
        default: "no"
        type: choice
        options:
          - "yes"
          - "no"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ github.event.inputs.node-version }}

      - name: Install dependencies
        run: |
          npm install

      - name: Enable KVM
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: Run Android Emulator
        uses: ReactiveCircus/android-emulator-runner@v2.32.0
        with:
          api-level: 31
          target: google_apis
          arch: x86_64
          profile: Nexus 6
          script: |
            echo "Installing App"
            adb install "app/Demo app.apk"
            adb wait-for-device
            adb shell input keyevent 82
            echo "Running WDIO + Cucumber Tests"
            npx wdio run ./wdio.conf.js

      - name: Generate report
        if: ${{ github.event.inputs.generate-report == 'yes' }}
        run: npm run report

      - name: Upload test report
        if: ${{ github.event.inputs.generate-report == 'yes' }}
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: |
            ./reports
